USE [master]
GO

/****** Object:  Database [RestaurantMgmt_Min]    Script Date: 25/09/2025 3:28:40 CH ******/
CREATE DATABASE [RestaurantMgmt_Min]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RestaurantMgmt_Min', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\RestaurantMgmt_Min.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RestaurantMgmt_Min_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\RestaurantMgmt_Min_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RestaurantMgmt_Min].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RestaurantMgmt_Min] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RestaurantMgmt_Min] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RestaurantMgmt_Min] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RestaurantMgmt_Min] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RestaurantMgmt_Min] SET ARITHABORT OFF 
GO

ALTER DATABASE [RestaurantMgmt_Min] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RestaurantMgmt_Min] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RestaurantMgmt_Min] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RestaurantMgmt_Min] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RestaurantMgmt_Min] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RestaurantMgmt_Min] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RestaurantMgmt_Min] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RestaurantMgmt_Min] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RestaurantMgmt_Min] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RestaurantMgmt_Min] SET  ENABLE_BROKER 
GO

ALTER DATABASE [RestaurantMgmt_Min] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RestaurantMgmt_Min] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RestaurantMgmt_Min] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RestaurantMgmt_Min] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RestaurantMgmt_Min] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RestaurantMgmt_Min] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RestaurantMgmt_Min] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RestaurantMgmt_Min] SET RECOVERY FULL 
GO

ALTER DATABASE [RestaurantMgmt_Min] SET  MULTI_USER 
GO

ALTER DATABASE [RestaurantMgmt_Min] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RestaurantMgmt_Min] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RestaurantMgmt_Min] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RestaurantMgmt_Min] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [RestaurantMgmt_Min] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RestaurantMgmt_Min] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [RestaurantMgmt_Min] SET QUERY_STORE = ON
GO

ALTER DATABASE [RestaurantMgmt_Min] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [RestaurantMgmt_Min] SET  READ_WRITE 
GO

